### PR TITLE
simplify schedule reference counting.

### LINKED ISSUE #379: panic in RawTask drop_task
Hello! I'm using glommio to experiment with async rust and especially asynchronous file IO. While trying to implement write ahead log I faced strange panic in drop_task [here](https://github.com/DataDog/glommio/blob/master/glommio/src/task/raw.rs#L347) in assertion [here](https://github.com/DataDog/glommio/blob/master/glommio/src/task/raw.rs#L295)

I'm using current master branch at ```cb1094189d03e911c77deaebe861ad3ab8ae57e6``` with rustc: ```rustc 1.55.0-nightly (e82b65026 2021-06-20)```

Test I'm using to reproduce an error https://github.com/LizardWizzard/parsley/blob/feature/initial-wal/core/src/wal/segment.rs#L475

Backtrace:
```
running 1 test
thread 'wal::segment::test::read_write_segment' panicked at 'assertion failed: `(left != right)`
  left: `0`,
 right: `0`', /home/dmitry/src/glommio/glommio/src/task/raw.rs:351:20
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/panicking.rs:92:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/panicking.rs:117:5
   4: glommio::task::raw::RawTask<F,R,S>::decrement_references
             at /home/dmitry/src/glommio/glommio/src/task/raw.rs:295:9
   5: glommio::task::raw::RawTask<F,R,S>::drop_task
             at /home/dmitry/src/glommio/glommio/src/task/raw.rs:351:20
   6: glommio::task::raw::RawTask<F,R,S>::run
             at /home/dmitry/src/glommio/glommio/src/task/raw.rs:497:17
   7: glommio::task::task_impl::Task::run
             at /home/dmitry/src/glommio/glommio/src/task/task_impl.rs:115:18
   8: glommio::executor::LocalExecutor::run_one_task_queue
             at /home/dmitry/src/glommio/glommio/src/executor/mod.rs:1074:25
   9: glommio::executor::LocalExecutor::run_task_queues
             at /home/dmitry/src/glommio/glommio/src/executor/mod.rs:1037:17
  10: glommio::executor::LocalExecutor::run::{{closure}}
             at /home/dmitry/src/glommio/glommio/src/executor/mod.rs:1164:27
  11: scoped_tls::ScopedKey<T>::set
             at /home/dmitry/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  12: glommio::executor::LocalExecutor::run
             at /home/dmitry/src/glommio/glommio/src/executor/mod.rs:1143:9
  13: core::wal::segment::test::read_write_segment
             at ./src/wal/segment.rs:478:9
  14: core::wal::segment::test::read_write_segment::{{closure}}
             at ./src/wal/segment.rs:475:5
  15: core::ops::function::FnOnce::call_once
             at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ops/function.rs:227:5
  16: core::ops::function::FnOnce::call_once
             at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'wal::segment::test::read_write_segment' panicked at 'assertion failed: `(left != right)`
  left: `0`,
 right: `0`', /home/dmitry/src/glommio/glommio/src/task/raw.rs:351:20
stack backtrace:
   0:     0x55f285069350 - std::backtrace_rs::backtrace::libunwind::trace::hfa838fc631229987
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55f285069350 - std::backtrace_rs::backtrace::trace_unsynchronized::h93a23e36ec026219
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55f285069350 - std::sys_common::backtrace::_print_fmt::hba56c7f796a4152f
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55f285069350 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h214637f1e26310e1
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55f28508d19c - core::fmt::write::h7aa6cd0067dca82a
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/fmt/mod.rs:1110:17
   5:     0x55f285066095 - std::io::Write::write_fmt::heb07fc0616bbd06d
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/io/mod.rs:1640:15
   6:     0x55f28506b93b - std::sys_common::backtrace::_print::h2c2441c37e894fb5
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55f28506b93b - std::sys_common::backtrace::print::h4fb679ac439362ea
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55f28506b93b - std::panicking::default_hook::{{closure}}::h56bbadec2356e5d2
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/panicking.rs:208:50
   9:     0x55f28506b411 - std::panicking::default_hook::hb25822b45f6fdc4e
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/panicking.rs:225:9
  10:     0x55f28506c004 - std::panicking::rust_panic_with_hook::h4da5578e7277d2d4
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/panicking.rs:622:17
  11:     0x55f28506bae7 - std::panicking::begin_panic_handler::{{closure}}::h003783ddb3cba4e8
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/panicking.rs:519:13
  12:     0x55f28506982c - std::sys_common::backtrace::__rust_end_short_backtrace::hd138d2032731ed21
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55f28506ba49 - rust_begin_unwind
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/panicking.rs:515:5
  14:     0x55f284e22ba1 - core::panicking::panic_fmt::hbe99dddd3092ba3c
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/panicking.rs:92:14
  15:     0x55f28508bab8 - core::panicking::assert_failed_inner::h4fdb1013d187f202
  16:     0x55f284ff0afa - core::panicking::assert_failed::h44bf3100291815e3
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/panicking.rs:117:5
  17:     0x55f284e7dc93 - glommio::task::raw::RawTask<F,R,S>::decrement_references::ha735ffa7319dc6c7
                               at /home/dmitry/src/glommio/glommio/src/task/raw.rs:295:9
  18:     0x55f284e9309c - glommio::task::raw::RawTask<F,R,S>::drop_task::h5e5a6a279af25816
                               at /home/dmitry/src/glommio/glommio/src/task/raw.rs:351:20
  19:     0x55f284f913c2 - <glommio::task::task_impl::Task as core::ops::drop::Drop>::drop::h015ecd7dfe32f37b
                               at /home/dmitry/src/glommio/glommio/src/task/task_impl.rs:138:13
  20:     0x55f284f8b9ab - core::ptr::drop_in_place<glommio::task::task_impl::Task>::h8fe754e2829cc815
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  21:     0x55f284f8c60f - core::ptr::drop_in_place<[glommio::task::task_impl::Task]>::hd46eae2bf3ea54ef
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  22:     0x55f284f9031f - <alloc::collections::vec_deque::VecDeque<T> as core::ops::drop::Drop>::drop::hdc360fa69ffb4ad9
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/alloc/src/collections/vec_deque/mod.rs:135:13
  23:     0x55f284f8d6b7 - core::ptr::drop_in_place<alloc::collections::vec_deque::VecDeque<glommio::task::task_impl::Task>>::h1f2e84f01247f0ba
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  24:     0x55f284f8a58b - core::ptr::drop_in_place<core::cell::UnsafeCell<alloc::collections::vec_deque::VecDeque<glommio::task::task_impl::Task>>>::ha8a5e67119df61f1
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  25:     0x55f284f8a48f - core::ptr::drop_in_place<core::cell::RefCell<alloc::collections::vec_deque::VecDeque<glommio::task::task_impl::Task>>>::he6db19826e870cb4
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  26:     0x55f284f8c6db - core::ptr::drop_in_place<glommio::executor::multitask::LocalQueue>::h9b79bc4e923b8139
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  27:     0x55f284f8c7ab - core::ptr::drop_in_place<glommio::executor::multitask::LocalExecutor>::hd489bdeafaade895
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  28:     0x55f284f8dc36 - <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop::h22d711c0cc74e700
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/alloc/src/rc.rs:1439:17
  29:     0x55f284f8d27b - core::ptr::drop_in_place<alloc::rc::Rc<glommio::executor::multitask::LocalExecutor>>::h0362f48f451bcab3
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  30:     0x55f284f8b577 - core::ptr::drop_in_place<glommio::executor::TaskQueue>::hff7064ef2941e6cc
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  31:     0x55f284f8cdfb - core::ptr::drop_in_place<core::cell::UnsafeCell<glommio::executor::TaskQueue>>::hb01b043f964cefc4
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  32:     0x55f284f8cc5f - core::ptr::drop_in_place<core::cell::RefCell<glommio::executor::TaskQueue>>::h60e69de0d9b7fd14
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  33:     0x55f284f8dd76 - <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop::h2a1ae6df2443e44b
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/alloc/src/rc.rs:1439:17
  34:     0x55f284f8d68b - core::ptr::drop_in_place<alloc::rc::Rc<core::cell::RefCell<glommio::executor::TaskQueue>>>::hb77eed961a88aa2f
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  35:     0x55f284f8a4d3 - core::ptr::drop_in_place<core::option::Option<alloc::rc::Rc<core::cell::RefCell<glommio::executor::TaskQueue>>>>::h1a516687e5c96287
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  36:     0x55f284f8bf4e - core::ptr::drop_in_place<glommio::executor::ExecutorQueues>::hc16c72e3a0135775
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  37:     0x55f284f8d0bb - core::ptr::drop_in_place<core::cell::UnsafeCell<glommio::executor::ExecutorQueues>>::ha44ac7312e556af8
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  38:     0x55f284f8cf0f - core::ptr::drop_in_place<core::cell::RefCell<glommio::executor::ExecutorQueues>>::h85328fb414f89dd5
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  39:     0x55f284f8e1a6 - <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop::h44dbc92ab2302cae
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/alloc/src/rc.rs:1439:17
  40:     0x55f284f89deb - core::ptr::drop_in_place<alloc::rc::Rc<core::cell::RefCell<glommio::executor::ExecutorQueues>>>::hc0a261eef33e2eda
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  41:     0x55f284f8ba67 - core::ptr::drop_in_place<glommio::executor::LocalExecutor>::ha4a111ef6e89286b
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  42:     0x55f284eeeeed - core::wal::segment::test::read_write_segment::hfe10b8908a43af98
                               at /home/dmitry/src/parsley/core/src/wal/segment.rs:552:5
  43:     0x55f284e6293a - core::wal::segment::test::read_write_segment::{{closure}}::h24d25ed8f5391e7e
                               at /home/dmitry/src/parsley/core/src/wal/segment.rs:475:5
  44:     0x55f284e6572e - core::ops::function::FnOnce::call_once::h0b3c0e0fa7386ef8
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ops/function.rs:227:5
  45:     0x55f284f193f3 - core::ops::function::FnOnce::call_once::h27530275e622330b
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ops/function.rs:227:5
  46:     0x55f284f193f3 - test::__rust_begin_short_backtrace::h44c82cc7d0f4937d
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/test/src/lib.rs:577:5
  47:     0x55f284f17e8c - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h20c7d4b3f228af07
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/alloc/src/boxed.rs:1575:9
  48:     0x55f284f17e8c - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hbecd070b87bd6780
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/panic.rs:347:9
  49:     0x55f284f17e8c - std::panicking::try::do_call::h5b1333e8bd607b9c
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/panicking.rs:401:40
  50:     0x55f284f17e8c - std::panicking::try::h057fd2077bd509e5
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/panicking.rs:365:19
  51:     0x55f284f17e8c - std::panic::catch_unwind::h2f57d52ee610e8fc
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/panic.rs:434:14
  52:     0x55f284f17e8c - test::run_test_in_process::h9a32ca2677c7f812
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/test/src/lib.rs:600:18
  53:     0x55f284f17e8c - test::run_test::run_test_inner::{{closure}}::hb449ab58fec32d94
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/test/src/lib.rs:492:39
  54:     0x55f284ef1482 - test::run_test::run_test_inner::{{closure}}::h08d55d9698ad3c92
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/test/src/lib.rs:519:37
  55:     0x55f284ef1482 - std::sys_common::backtrace::__rust_begin_short_backtrace::h739a7c7a988c8471
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/sys_common/backtrace.rs:125:18
  56:     0x55f284ef5088 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hff87f6709b4599d6
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/thread/mod.rs:481:17
  57:     0x55f284ef5088 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::heedb21d3eb169296
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/panic.rs:347:9
  58:     0x55f284ef5088 - std::panicking::try::do_call::h74a412fd6dfdff13
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/panicking.rs:401:40
  59:     0x55f284ef5088 - std::panicking::try::h90801934282c25f3
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/panicking.rs:365:19
  60:     0x55f284ef5088 - std::panic::catch_unwind::hee752c1088dd1104
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/panic.rs:434:14
  61:     0x55f284ef5088 - std::thread::Builder::spawn_unchecked::{{closure}}::h36779ab69c69bb28
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/thread/mod.rs:480:30
  62:     0x55f284ef5088 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h3dcc0d5454468332
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ops/function.rs:227:5
  63:     0x55f285071a77 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd1f9b751a68dd2ac
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/alloc/src/boxed.rs:1575:9
  64:     0x55f285071a77 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h22d732940e85619f
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/alloc/src/boxed.rs:1575:9
  65:     0x55f285071a77 - std::sys::unix::thread::Thread::new::thread_start::h04c7a9e17ed1032c
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/sys/unix/thread.rs:71:17
  66:     0x7f956b77a299 - <unknown>
  67:     0x7f956b555353 - <unknown>
  68:                0x0 - <unknown>
thread panicked while panicking. aborting.
```

Any tips on how to debug this kind of situation? E g how to detect which task is causing the issue. Maybe I'm using something incorrectly. Thanks in advance!

### PR DESCRIPTION
**Pull request by glommer**
There are a couple of places in which we are trying to be way too smart
about schedule reference counts: because we will also decrement it for
some reason (because we are dropping a waker or the task), we don't
increment the ref count at that point. To allow for such optimization,
schedule() itself cannot bump the reference count, which has to be left
to the caller.

I get it, atomics are expensive. But unlike the crate that inspired us
with this task code, our executors are always local. There is contention
on channel wake up, that's true, but that should not be nearly as bad as
contention on every operation.

Even if it were, given that we already had a bad bug in this area, I
say simplicity wins.

Our user Dmitry recently opened an issue (379) with one such bug. That
bug started with a double schedule, but even after that was fixed we
still crashed. And that's essentially because we didn't bump the
refcount when called through wake_by_ref.

The code should be a lot more resilient now, more future proof, and
if there are a couple of extra cycles from a relaxed atomic, so be it.

Fixes #379

### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Related issues

A list of issues either fixed, containing architectural discussions, otherwise relevant
for this Pull Request.

### Additional Notes

Anything else we should know when reviewing?

### Checklist

[] I have added unit tests to the code I am submitting
[] My unit tests cover both failure and success scenarios
[] If applicable, I have discussed my architecture

### CODE REVIEW

File: glommio/src/task/raw.rs [hunk 1]
```diff
@@ -365,6 +353,7 @@ where
     /// task reference to its schedule function.
     unsafe fn schedule(ptr: *const ()) {
         let raw = Self::from_ptr(ptr);
+        Self::increment_references(&mut *(raw.header as *mut Header));
 
         let guard;
         // Calling of schedule functions itself does not increment references,
```
Comment (LizardWizzard) [inline glommio/src/task/raw.rs:359]: Is this still valid?

Comment (glommer) [reply glommio/src/task/raw.rs:359]: yes, the whole point of the PR is to move the increment inside schedule, and take out the ones that happen in the callers
